Add a method of enabling or disabling containers using labels
containrrr/watchtower pull request #104
Opened 2017-10-17 04:56 UTC by belak

This would potentially be a better way of handling #102, #95, #58, and #4.

I haven't tested this yet and there may be a cleaner way of doing this, but it seems like a relatively simple concept.

2017-10-17 04:59 UTC, belak commented
This adds two features:

* A label (`com.centurylinklabs.watchtower.enable`) which lets users specify if a container should be enabled or not on a per-container basis.
* A command line option, `--no-enable` which will let watchtower start up without watching any specific containers (unless they're specifically enabled with labels)

2017-10-30 04:51 UTC, voglster commented
+1 this, was going to write my own adding functionality similar to this until I saw this PR.  for now I'm testing belak's branch.

2017-11-07 01:37 UTC, chriswue requested changes
There is an option name bug which needs fixing but otherwise the changes look good to me.

2017-11-07 01:37 UTC, chriswue commented on main.go
> +	client = container.NewClient(!c.GlobalBool("no-pull"), !c.GlobalBool("no-watch"))
The command line option is "no-enable" while this looks for "no-watch". In fact I'd probably prefer a slightly more verbose option name like "no-watch-by-default"

2017-11-09 15:43 UTC, Nightbr commented
Any news on this, it's a real killer feature needed for watchtower!

2017-11-09 16:05 UTC, stffabi commented
@belak thanks for your contribution and thanks @chriswue for reviewing it.

I like the idea of @Nightbr to rename the flag to `--label-enable` and then only take labeled containers. I think this would be much more intuitive for the user.

On the other hand having a possibility to exclude is also handy. Maybe we could implement an include and exclude option for named lables, e.g. `--include-label mylabel` and `--exclude-label myExcludeLabel`. Specifying no include labels means all containers, and one can exclude some others based on exclude labels.

And we should also include the new command line parameter and the documentation to the readme.md

2017-11-27 08:26 UTC, stffabi commented
Any opinions how we should proceed? Should we go the `include` `exclude` way, or do you prefer some other handling?

2017-11-27 08:30 UTC, belak commented
Sorry, I've been busy with other stuff lately. At least for me, the simplest way to handle this would be `--label-enable` and that would be good enough for me. A full include/exclude seems like it might be overcomplicating this.

Also, do you have any instructions on how to run this manually for testing? Do you just use it outside a docker container manually?

2017-11-27 08:46 UTC, stffabi requested changes

2017-11-27 08:46 UTC, stffabi commented on main.go
> +			Usage:  "decide which containers to watch based on a label",
Could you add which label we use here?

2017-11-27 08:47 UTC, stffabi commented
@belak I'm fine with that 😄. Would it be possible for you to add the corresponding documentation in the readme.md? And I've made another small comment.

Apart from that LGTM, and I'm looking forward to merge this.

2017-11-27 08:49 UTC, stffabi commented
For testing I always use it outside of a docker container. That works quite well.

2017-11-27 09:27 UTC, belak commented
I'm open to any updates in wording... this was just thrown together based on the other documentation.

2017-11-28 07:24 UTC, stffabi commented
LGTM, thanks again for your contribution. I'm going to squash the commits and will then merge it in.

2017-11-28 07:29 UTC, stffabi approved these changes

2017-11-28 07:30 UTC, merged