feat: improve HTTP API logging, honor no-startup-message
containrrr/watchtower pull request #1091
Opened 2021-10-11 19:25 UTC by Artanicus

They provide little useful information outside debugging and anything at
Info level is broadcast over shoutrrr.

2021-10-15 14:45 UTC, piksel commented
I don't think it is that straight forward. It essentially replaces the startup message and when `--debug` isn't passed, there is no output from starting watchtower at all which might be confusing for some users. That being said, the startup message should probably be displayed, but incorporating whether the API is enabled. That way you could disable it as well using `--no-startup-message`.

2021-10-15 21:37 UTC, simonaronsson requested changes
I agree with @piksel on this.

2021-10-23 06:32 UTC, jinnatar commented
ACK, reworking it to use `--no-startup-message`

2021-10-23 13:43 UTC, jinnatar commented
@piksel PTAL. I left the `runHTTPServer` logging as Debug since it's of questionable value to a user, and changed the `Info` level log to contain the listen port so it's more useful in indicating the API is functioning and where to find it.

Example run:
```
%> ./watchtower daemon --http-api-update --http-api-token foo --http-api-periodic-polls --no-startup-message
INFO[0001] Watchtower v0.0.0-unknown                     notify=no
INFO[0001] Using no notifications                        notify=no
INFO[0001] Only checking containers with name "daemon"   notify=no
INFO[0001] Scheduling first run: 2021-10-24 16:29:02 +0300 EEST  notify=no
INFO[0001] Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds  notify=no
INFO[0001] The HTTP API is enabled at :8080.             notify=no
```

2021-10-23 13:48 UTC, jinnatar commented
There is still a slight annoyance left where watchtower is very silent and unhelpful, but I believe this is a deeper issue than I can resolve here:
```
%> ./watchtower daemon --http-api-update --http-api-token foo 
<absolutely no output produced>
```

i.e. if the API mode is enabled but no periodic updates are enabled as is the default, startup messages aren't processed at all since the call is blocked. Probably they should still happen, but then the flow needs to be changed a bit and my Go isn't exactly that good to do it in this PR without undue risk to general stability. :-)

Edit: nvm, found a clean way to fix this issue at the same time.

2021-10-24 13:58 UTC, piksel requested changes
Looks good, except for a few smaller things.

The API parts are messy and should be redone (ref #939). But this should be sufficient for now. Just take a look at the comments.

2021-10-24 13:58 UTC, piksel commented on cmd/root.go
> +	enableAPIPeriodicPolls, _ := c.PersistentFlags().GetBool("http-api-periodic-polls")
Why make another copy of the flag?

2021-10-24 13:58 UTC, piksel commented on pkg/api/api.go
> +	log.Debug("Serving HTTP")
```suggestion
```
I don't think this serves any purpose now

2021-10-24 13:58 UTC, piksel commented on cmd/root.go
> +	}
This is a bit weird when just starting with `--run-once`, as it will be followed by said update.

```suggestion
		if runOnce, _ := c.PersistentFlags().GetBool("run-once"); runOnce {
			startupLog.Info("Running a one time update.")
        	} else {
			startupLog.Info("Periodic runs are not enabled.")
		}
	}
```

It should probably be `else if` etc. but that's not supported by GitHub suggestions...

2021-10-25 12:11 UTC, jinnatar commented on cmd/root.go
> +	enableAPIPeriodicPolls, _ := c.PersistentFlags().GetBool("http-api-periodic-polls")
Because I was being blind and didn't notice `unblockHTTPAPI ` was already there. Will fix.

2021-10-25 12:11 UTC, jinnatar commented on cmd/root.go
> +	}
It made sense to me, but you could be right that not to anyone else so better to be more helpful. Added the else if version.

2021-11-04 13:24 UTC, piksel approved these changes

2021-11-28 19:08 UTC, Artanicus commented
> I agree with @piksel on this.

I believe these have been addressed but GitHub still marks this comment as blocking merge for some reason.

2021-11-29 09:33 UTC, simskij approved these changes

2021-11-29 14:07 UTC, merged