fix: move invalid token to log field
containrrr/watchtower pull request #1171
Opened 2021-12-20 13:11 UTC by piksel

Prevents potential log manipulation. Probably not a realistic concern, but fixing it is easier than dismissing the warnings.

2021-12-20 13:59 UTC, piksel commented
😩 

Welp, this PR actually does escape the input as a "safe" go-string, which should not trigger CWE-117 (all non-text characters are escaped, including newlines etc.).
So even if this fixes the potential issue, it still does not clear the warning (and even introduces another warning since we are outputting the HTTP headers).

2021-12-27 11:22 UTC, simskij commented
Soo, are we closing this, or are you still looking to continue at some point?

2021-12-27 12:00 UTC, piksel commented
Well, it *is* escaped (using %q). Not sure how we could escape it in a way that doesn't trigger the security rule. I think it's marginally better in this version, since it's clearly distinguished from an actual log message, but we could also just remove it all together.

2021-12-27 13:30 UTC, simskij commented
I think I prefer the second option

2022-01-22 16:44 UTC, simskij requested changes

2022-01-22 16:44 UTC, simskij commented on pkg/api/api.go
> +			}).Tracef("Invalid Authorization header")
```suggestion
```

2022-01-22 16:50 UTC, merged