Update container-selection.md
containrrr/watchtower pull request #1380
Opened 2022-09-10 18:43 UTC by andriibratanin

Fix list formatting for https://containrrr.dev/watchtower/container-selection/ page

2022-09-10 18:44 UTC, zoispag approved these changes

2022-09-10 18:46 UTC, zoispag commented
@all-contributors add @andriibratanin for docs

2023-09-18 12:19 UTC, 0220tiezo1323 requested changes
No

2023-11-11 13:34 UTC, piksel approved these changes

2023-11-11 13:34 UTC, merged