Networkmode service
containrrr/watchtower pull request #1429
Opened 2022-10-17 16:06 UTC by schizo99

This PR solves the issue when using `network_mode: service:xxxxx` in a service.
It closes #1286 

For this to work not only does the label `com.centurylinklabs.watchtower.depends-on` be set to the parent container. It also require a new label `com.centurylinklabs.watchtower.network-service` to be set.

It solves the issue by updating the HostConfig with the ID of the new parent container.

2022-10-18 08:33 UTC, schizo99 commented
I think I have found a better way to solve this.

Will update PR later on.

2022-10-18 14:47 UTC, schizo99 commented
Maybe did a mistake by force pushing?

In any case I think this new approach is nicer and does not require any additional labels.

2022-10-19 08:58 UTC, piksel requested changes
This seems like it *should* work. The only thing I am not thrilled about is that the API for getting the container info also alters the returned info. The way it's used right now, this shouldn't be an issue, but it's hidden/unexpected, which could lead to bugs further on.

Of course, the "right" way would be to do this when preparing the new configuration before starting the container. Except that at that time, the old container should already have been removed.

2022-10-19 08:58 UTC, piksel commented on pkg/container/client.go
> +	if len(containerNetworkMode) == 2 {
```suggestion
	if len(containerNetworkMode) == 2 && containerNetworkMode[0] == "container" {
```
if this contains some other prefix that we don't know about, we should probably leave it alone

2022-10-19 08:58 UTC, piksel commented on pkg/container/client.go
> +		containerInfo.HostConfig.NetworkMode = container.NetworkMode(fmt.Sprintf("container:%s", parentContainer.Name))
```suggestion
		} else {
			containerInfo.HostConfig.NetworkMode = container.NetworkMode(fmt.Sprintf("container:%s", parentContainer.Name))
		}
```

If we don't get a parentContainer we shouldn't be updating the `NetworkMode`. In fact, the container should probably be skipped with an error if this happens, but at least this way will just fall back to the old (current) behaviour of watchtower.

2022-10-19 10:25 UTC, schizo99 commented
You're right. I'm not 100% sold on this but it's the most efficient way.
It might, as you say, cause issues should the Docker API change from allowing name or id in the network_mode.

The other option would be my first approach which would require an additional label to be added besides the depends_on label.

2022-10-20 07:58 UTC, piksel approved these changes
It still needs tests, but otherwise I am happy with this. Changing the `container:ContainerID` to `container:ContainerName` is in a way more correct, even if it's not what the raw inspect contained.

2022-10-24 13:46 UTC, schizo99 commented
Was intending to add tests.

However, as soon as I update the `container_watchtower.json` and change network_mode to `container:xxxxx` the server throws this error.

<details>
<summary>Go test thrown errors</summary>

```
(cloud) {15:37}~/fab/watchtower/pkg/container:networkmode-service ✗ ➭ go test -v
=== RUN   TestContainer
Running Suite: Container Suite
==============================
Random Seed: 1666618638
Will run 44 of 44 specs

•••••WARN[0000] Failed to retrieve container image info: request returned Internal Server Error for API route and version http://127.0.0.1:33371/v1.41/images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json, check if the server supports the requested API version 

------------------------------
• Failure [0.003 seconds]
the client
/home/aahp/fab/watchtower/pkg/container/client_test.go:23
  when listing containers
  /home/aahp/fab/watchtower/pkg/container/client_test.go:72
    when no filter is provided
    /home/aahp/fab/watchtower/pkg/container/client_test.go:73
      should return all available containers [It]
      /home/aahp/fab/watchtower/pkg/container/client_test.go:74

      Path mismatch
      Expected
          <string>: /v1.41/containers/xxxxxxxxxxxxxxxxxxxx/json
      to have suffix
          <string>: /images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json

      /home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21.1/ghttp/handlers.go:51
------------------------------
WARN[0000] Failed to retrieve container image info: request returned Internal Server Error for API route and version http://127.0.0.1:38345/v1.41/images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json, check if the server supports the requested API version 
• Failure [0.001 seconds]
the client
/home/aahp/fab/watchtower/pkg/container/client_test.go:23
  when listing containers
  /home/aahp/fab/watchtower/pkg/container/client_test.go:72
    when a filter matching nothing
    /home/aahp/fab/watchtower/pkg/container/client_test.go:86
      should return an empty array [It]
      /home/aahp/fab/watchtower/pkg/container/client_test.go:87

      Path mismatch
      Expected
          <string>: /v1.41/containers/xxxxxxxxxxxxxxxxxxxx/json
      to have suffix
          <string>: /images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json

      /home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21.1/ghttp/handlers.go:51
------------------------------
WARN[0000] Failed to retrieve container image info: request returned Internal Server Error for API route and version http://127.0.0.1:35389/v1.41/images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json, check if the server supports the requested API version 
• Failure [0.002 seconds]
the client
/home/aahp/fab/watchtower/pkg/container/client_test.go:23
  when listing containers
  /home/aahp/fab/watchtower/pkg/container/client_test.go:72
    when a watchtower filter is provided
    /home/aahp/fab/watchtower/pkg/container/client_test.go:100
      should return only the watchtower container [It]
      /home/aahp/fab/watchtower/pkg/container/client_test.go:101

      Path mismatch
      Expected
          <string>: /v1.41/containers/xxxxxxxxxxxxxxxxxxxx/json
      to have suffix
          <string>: /images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json

      /home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21.1/ghttp/handlers.go:51
------------------------------
WARN[0000] Failed to retrieve container image info: request returned Internal Server Error for API route and version http://127.0.0.1:42385/v1.41/images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json, check if the server supports the requested API version 
• Failure [0.002 seconds]
the client
/home/aahp/fab/watchtower/pkg/container/client_test.go:23
  when listing containers
  /home/aahp/fab/watchtower/pkg/container/client_test.go:72
    when include stopped is enabled
    /home/aahp/fab/watchtower/pkg/container/client_test.go:113
      should return both stopped and running containers [It]
      /home/aahp/fab/watchtower/pkg/container/client_test.go:114

      Path mismatch
      Expected
          <string>: /v1.41/containers/xxxxxxxxxxxxxxxxxxxx/json
      to have suffix
          <string>: /images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json

      /home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21.1/ghttp/handlers.go:51
------------------------------
WARN[0000] Failed to retrieve container image info: request returned Internal Server Error for API route and version http://127.0.0.1:45507/v1.41/images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json, check if the server supports the requested API version 
• Failure [0.001 seconds]
the client
/home/aahp/fab/watchtower/pkg/container/client_test.go:23
  when listing containers
  /home/aahp/fab/watchtower/pkg/container/client_test.go:72
    when include restarting is enabled
    /home/aahp/fab/watchtower/pkg/container/client_test.go:126
      should return both restarting and running containers [It]
      /home/aahp/fab/watchtower/pkg/container/client_test.go:127

      Path mismatch
      Expected
          <string>: /v1.41/containers/xxxxxxxxxxxxxxxxxxxx/json
      to have suffix
          <string>: /images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json

      /home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21.1/ghttp/handlers.go:51
------------------------------
WARN[0000] Failed to retrieve container image info: request returned Internal Server Error for API route and version http://127.0.0.1:39927/v1.41/images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json, check if the server supports the requested API version 
• Failure [0.001 seconds]
the client
/home/aahp/fab/watchtower/pkg/container/client_test.go:23
  when listing containers
  /home/aahp/fab/watchtower/pkg/container/client_test.go:72
    when include restarting is disabled
    /home/aahp/fab/watchtower/pkg/container/client_test.go:139
      should not return restarting containers [It]
      /home/aahp/fab/watchtower/pkg/container/client_test.go:140

      Path mismatch
      Expected
          <string>: /v1.41/containers/xxxxxxxxxxxxxxxxxxxx/json
      to have suffix
          <string>: /images/sha256:4dbc5f9c07028a985e14d1393e849ea07f68804c4293050d5a641b138db72daa/json

      /home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21.1/ghttp/handlers.go:51
------------------------------
• Failure [1.002 seconds]
the client
/home/aahp/fab/watchtower/pkg/container/client_test.go:23
  ExecuteCommand
  /home/aahp/fab/watchtower/pkg/container/client_test.go:153
    when logging
    /home/aahp/fab/watchtower/pkg/container/client_test.go:154
      should include container id field [It]
      /home/aahp/fab/watchtower/pkg/container/client_test.go:155

      Timed out after 1.001s.
      Got stuck at:
          ERRO[0000] Failed to extract command exec logs: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial http: unknown network http  containerID=ex-cont-id
          
      Waiting for:
          containerID="?ex-cont-id"?

      /home/aahp/fab/watchtower/pkg/container/client_test.go:218
------------------------------
••••••••••••••••••••••••••••••••

Summarizing 7 Failures:

[Fail] the client when listing containers when no filter is provided [It] should return all available containers 
/home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21.1/ghttp/handlers.go:51

[Fail] the client when listing containers when a filter matching nothing [It] should return an empty array 
/home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21.1/ghttp/handlers.go:51

[Fail] the client when listing containers when a watchtower filter is provided [It] should return only the watchtower container 
/home/aahp/go/pkg/mod/github.com/onsi/gomega@v1.21. [...]

2023-03-16 00:47 UTC, s-wasser commented
Any updates on this PR? Updating containers with service network mode is painful right now. Looking forward to seeing this get merged.

2023-03-16 09:38 UTC, piksel commented
@s-wasser it still needs tests, and I don't have enough knowledge of how docker network configuration changes the container info to fix it easily. I can take a look next time I get some free time though...

2023-04-23 07:02 UTC, shivindera commented
Any updates on this getting merged?

2023-04-23 08:47 UTC, piksel commented
@shivindera still needs tests. I have no idea if this actually works or not. The tests need to be there for us to be able to maintain this project. They tell us what some code is expected to do and how we can incorporate other changes without breaking this one's. I don't personally use this functionality myself, so it both requires extra time on reading up on and understanding the use cases, but it also means it would be guesses from my part in the end.

2023-07-23 09:44 UTC, Heisenberg2980 commented
@schizo99 any chance of getting this PR tested and merged? it seems you guys were really close last year, what is missing here to fix the issue?

2023-07-23 10:04 UTC, schizo99 commented
@Heisenberg2980 What's missing are tests for the new code. But I'm getting errors when implementing the tests.
See my previous [comment](https://github.com/containrrr/watchtower/pull/1429#issuecomment-1289061655)

2023-07-23 10:09 UTC, Heisenberg2980 commented
I would love to help but I have never implemented this type of tests myself. @piksel can you help with the errors @schizo99 is getting when trying to implement the test?

2023-07-24 09:49 UTC, piksel commented
@schizo99 if you can push the tests with the errors, I can probably fix them!

2023-07-24 18:27 UTC, schizo99 commented
@piksel I never got so far as to create any test cases for these changes since it started failing as soon as I modified the `NetworkMode` for the container in `container_watchtower.json`.

2023-07-25 18:24 UTC, piksel commented
To make the tests easier to write, I did some refactoring on the docker API server mock.
I ended up just writing a single test, and the only thing that is left un-tested is when the referenced container cannot be found.
I did at least add the integration test and the corresponding `docker-compose.yml` and could confirm that it was working with this fix.
Adding an additional test for when the container isn't found should be fairly trivial, but I don't have any more time today.

2023-07-27 16:26 UTC, Heisenberg2980 commented
Thank you very much @piksel, we are really close to have this PR merged and the issue fixed

2023-08-06 10:51 UTC, Heisenberg2980 commented
@piksel will you be able to add the additional test to get this PR merged?

2023-08-08 16:32 UTC, merged

2023-08-09 08:03 UTC, Heisenberg2980 commented
@piksel do you know when a new version containing this change will be released so we can test it?

2023-08-09 09:23 UTC, exilvm commented
> @piksel do you know when a new version of watchtower containing this change will be released so we can test it?

Use `latest-dev` image tag.