feat: allow logging output to use JSON formatter
containrrr/watchtower pull request #1705
Opened 2023-07-26 07:19 UTC by GridexX

**Title:** Enable JSON Logging - PR for Issue #28

**Description:**

This PR addresses and resolves the long-standing [issue #28](https://github.com/containrrr/watchtower/issues/28) in the `containrrr/watchtower` repository. The issue is related to enabling JSON logging for the application.

**Changes:**

- Added a new CLI argument `--json-logging` that enables the JSON log formatter for logging.
- Introduced the corresponding environment variable `WATCHTOWER_JSON_LOGGING` to control JSON logging behavior.
- Updated the documentation to reflect the new argument and its usage.

**Context:**

As this is my first-ever Pull Request, I'm excited to contribute to the `containrrr/watchtower` project. I'm building a log scraping application and enabling JSON logging will greatly facilitate log parsing and analysis in my use case.

**Testing:**

I have included comprehensive test coverage for the new argument in the `flags_test.go` file, ensuring proper functionality and compatibility with existing features.

I would greatly appreciate feedback and guidance on any improvements that can be made to this PR. Looking forward to contributing more to the project in the future! Thank you for considering this pull request.

2023-08-12 16:03 UTC, piksel requested changes

2023-08-12 16:03 UTC, piksel commented on cmd/root.go
> +	enableJsonFormatter, _ = f.GetBool("json-logging")
I really think this ought to be `--log-format json` or something similar, both to make it clear that this **replaces** the log output, and to make it easier to add additional logging formats without filling up with additional flags (and how would providing multiple logging format flags be even interpreted?)

If you go by this approach, the default value should be `auto`, since it changes the format based on whether the output is a TTL (interactive she'll) or not. The "text format" you referred to in the docs is commonly called `logfmt`.

2023-08-12 16:06 UTC, piksel commented
Apparently, I never submitted the review earlier. Sorry for the take-over.

Does my changes make sense? Again, sorry for the bad communication here.

2023-08-16 05:34 UTC, GridexX commented on cmd/root.go
> +	enableJsonFormatter, _ = f.GetBool("json-logging")
Hey there, @piksel! I wanted to express my gratitude for taking the time to review my pull request.

My intention behind this contribution was to cater to my personal use case. Therefore, I've incorporated an additional argument to enable the printing of logs in JSON format.

Your proposal offers a more modular approach, and the choice of variable name is crystal clear. Your feedback resonates with me, and I'm in agreement with the modifications. I'm perfectly comfortable with merging this pull request. :+1:

2023-08-17 11:07 UTC, piksel approved these changes

2023-09-16 15:23 UTC, merged