Add support for Gotify notifications
containrrr/watchtower pull request #346
Opened 2019-07-05 13:44 UTC by lukapeschke

This adds support for Gotify (https://gotify.net) notifications.

Work items:

* Two flags have been added to internal/flags/flags.go:
  "notification-gotify-url" and "notification-gotify-token".

* A Gotify notification driver has been added in
  notifications/gotify.go.

* "gotify" has been added to notification driver choices in
  notifications/notifier.go.

* Docs have been updated

2019-07-05 13:49 UTC, lukapeschke commented
Hi there! I'd like to add support for Gotify to watchtower in order to be able to get mobile notifications. 

If other people are interested in this, a review would be welcome!

Are there unit tests for notification drivers ? Or is there a way to trigger watchtower notification for testing purposes ?

Thanks!

2019-07-08 16:17 UTC, simskij commented
Good job! I'll review this. I'll also see if it'd be possible to integrate this into [shoutrrr](https://github.com/containrrr/shoutrrr) as that will replace our own notification implementations real soon.

2019-07-08 19:18 UTC, lukapeschke commented
Thanks! I'd be glad to help with the shoutrrr shoutrrr integration too If I can!

2019-07-08 21:04 UTC, simskij commented
> Thanks! I'd be glad to help with the shoutrrr shoutrrr integration too If I can!

That would be awesome! Feel free to check out the IFTTT and email services by @piksel. They are probably most up to date when it comes to implementation patterns and such.

2019-07-20 16:35 UTC, simonaronsson requested changes
Thank you for your very nice contribution! 🙏 
I've added a couple of minor change requests, but after that, it should be good to go (pun intended).

2019-07-20 16:35 UTC, simskij commented on notifications/gotify.go
> +			Title:    "WatchTower",
WatchTower -> Watchtower

2019-07-20 16:35 UTC, simskij commented on notifications/gotify.go
> +		resp, err := http.Post(n.getURL(), "application/json", bytes.NewBuffer([]byte(jsonBody)))
I'd prefer if you'd create the buffer before using it with the http client to improve readability.

2019-07-20 16:36 UTC, simskij commented
@all-contributors add lukapeschke for code and documentation

2019-07-22 08:14 UTC, lukapeschke commented
Thanks for the review @simskij ! Let me know if there are updates to do. I'll squash the commits once they look good to you :smiley: 

I've had a glance at shoutrrr, but haven't found the time to start coding yet. Should happen during the summer.

2019-07-22 10:25 UTC, simskij commented
LGTM 👍 
Feel free to rebase and squash and I'll make sure to merge it. 😄

2019-07-22 10:25 UTC, simonaronsson approved these changes

2019-07-22 12:22 UTC, lukapeschke commented
@simskij Done :smile:

2019-07-22 19:17 UTC, merged

2019-07-22 19:18 UTC, simskij commented
Thank you a lot for your contribution! 🙏