add --no-startup-message flag
containrrr/watchtower pull request #465
Opened 2020-03-13 09:42 UTC by lukwil

Added --no-startup-message flag.

I was not quite sure whether I should put it in NotificationFlags or SystemFlags. 
I went for NotificationFlags and documented it in the notification docs.

Fixes #443

2020-03-21 14:11 UTC, simonaronsson requested changes
Thank you so much for your solid contribution!

If you don't mind, I'd be really grateful if you could move this to `SystemFlags` and document it under `Arguments`. Sorry for adding additional work for you.

2020-03-22 16:20 UTC, lukwil commented
I just added a commit. I hope it fixes your remarks 😅

2020-03-22 20:39 UTC, simskij commented
LGTM. Thank you again!

2020-03-22 20:39 UTC, simonaronsson approved these changes

2020-03-22 20:40 UTC, simskij commented
@all-contributors add @lukwil for code

2020-03-22 20:40 UTC, merged

2020-03-24 22:29 UTC, aneisch commented
I'm still getting a startup email even with both environmental variable and `--no-startup-message`. Thoughts?

2020-03-25 09:17 UTC, simskij commented
Thanks! Would you mind creating a separate bug ticket for that?