Allows flags containing sensitive stuff to be passed as files
containrrr/watchtower pull request #545
Opened 2020-05-12 20:52 UTC by tammert

Potential fix for #532.

I've built in a check to see if the following sensitive options are passed to Watchtower as a file instead of a plaintext secret:
* notification-email-server-password
* notification-slack-hook-url
* notification-msteams-hook
* notification-gotify-token
* notification-url

If this is the case, the runtime value is converted to the contents of the file instead. As the potential for an unexpected conflict is really low (aka a plaintext password that's actually the same as a fully-qualified existing file on the system), it seemed a better option than adding 5 extra flags.

@simskij if you hate this idea and/or have better suggestions, let me know!

2020-05-22 14:04 UTC, simonaronsson requested changes
I like it! I only have two things I'd like to address before approving:

1. Would you mind fixing the linting issue?
2. Would be great if we could have a test or two verifying this behaves as expected (pref. both for a file and for a string)

I also noticed it's in need of a rebase to resolve some conflicts :)

2020-05-22 17:21 UTC, tammert commented
@simskij thanks for the feedback! I've added tests and fixed the linting issue. While creating the tests I found out that `--notification-url` is actually an array (would not have expected that from the name, maybe `--notications-urls` would be better?). Because of that, I couldn't really get an elegant solution in place for passing it as a file, so I've removed it from that functionality for now (and updated docs).

2020-05-25 10:51 UTC, simskij commented
> maybe `--notications-urls` would be better?
Now that it's out in production, as of 1.0.0, it's hard to change it without breaking peoples setups, but we could definitely alias it to `--notification-urls` as well, if that makes sense. 

> Because of that, I couldn't really get an elegant solution in place for passing it as a file, so I've removed it from that functionality for now (and updated docs).

Seems reasonable! I'll review as soon as I have some time on my hands. Great work, as usual 👍

2020-06-10 10:14 UTC, simonaronsson approved these changes

2020-06-10 10:14 UTC, merged

2020-06-10 17:22 UTC, piksel commented
Regarding the URLs, the reason for it being singular is probably because you would pass it multiple times for multiple values, and as such `--notification-url foo --notification-url bar` makes sense. But what was the problem with getting it to work elegantly?
My suggestions would be either pass `--notification-urls myurls.txt` which would load the URLs from a newline-separated file, or to use multiple `--notification-url myurl1.txt`  arguments, one for each file.

2020-06-10 18:15 UTC, simonaronsson commented
> Regarding the URLs, the reason for it being singular is probably because you would pass it multiple times for multiple values, and as such `--notification-url foo --notification-url bar` makes sense. But what was the problem with getting it to work elegantly?
> 
> My suggestions would be either pass `--notification-urls myurls.txt` which would load the URLs from a newline-separated file, or to use multiple `--notification-url myurl1.txt`  arguments, one for each file.

I think the issue was that while that approach works well for flags, it won’t work with env vars as they will just overwrite each other.

2020-06-10 19:24 UTC, piksel commented
Oh, I just figured that was part of anaconda/viper, but I guess it's a single argument for command line as well then?

Update: No, it is indeed viper magic: [spf13/viper/issues/339](https://github.com/spf13/viper/issues/339)

2020-06-10 19:33 UTC, tammert commented
So my main issues when working with this PR were:
1) finding out at the end of the road that `--notification-url` was not a String but a StringArray, which made it incompatible with the func I had written
2) I couldn't find a way to set the value of a StringArray in the same way as I could for a String: https://github.com/containrrr/watchtower/blob/12d323354f222d8c4a0b5b852f15a475d943cd2b/internal/flags/flags.go#L400

I'm sure we can figure out a proper solution to those two issues though. I'd be happy to give that some more attention, but it would indeed by good to track it in a new issue/PR.