set default registry server-addres for Docker HUB images
containrrr/watchtower pull request #55
Opened 2017-01-26 20:44 UTC by rreinurm

Current Docker HUB users can't pull private DockerHUB images without specifying docker image with server path like "index.docker.io/rreinurm/private-image". But in docker-compose and docker commands don't require to explicitly specify DockerHUB registry-address for private images, I would just use imagename "rreinurm/private-image".

This pull request appends "index.docker.io" as a default registry-server address to the docker image name to be able to pull them with same ux as docker commands.

2017-01-29 19:23 UTC, stffabi commented
Thanks @rreinurm for your contribution.
This really seems to be an issue, but I would prefer not to fix the images onto `index.docker.io` at this location. I think we should left these image names untouched and rather fallback to the default registry in `trust.go`, if no registry is defined in the image. That's the place where the login credentials are determined. Furthermore accordingly to this comment https://github.com/docker/docker/blob/e9c0de0de65182915d1cd205f06f5c903c20a29f/cli/command/registry.go#L24 the default registry may depend on the platform. As a result we should also call `/info` to determine the default registry, similarly as in the linked `registry.go`.

@rreinurm would it be possible for you to change the implementation of the PR?

2017-01-29 19:24 UTC, stffabi requested changes
See previous comment.

2017-01-30 20:54 UTC, rreinurm commented
sure, I will refactor my implementation

2017-01-31 07:54 UTC, stffabi commented
That's great, thanks.

2017-02-27 21:15 UTC, stffabi commented
@rreinurm just wanted to ask back if you did find some spare time to change your implementation?

2017-03-16 12:49 UTC, wmbutler commented
Seems like the easiest way to handle this would be to grab the value off the `~/.docker/config.json` file since it's already present.

```json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "d21idXRsZXI6dzRjb3gyaXY="
                }
        }
}
```

2017-03-16 12:50 UTC, wmbutler commented
Seems like it would be easiest to grab this off `~/.docker/config.json` since it's already present:

```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "lkfjljfrfjrferofjeo"
                }
        }
}
```

2017-06-06 16:29 UTC, morpheus65535 commented
@stffabi Is there an ETA for this to be include in a release?

2019-04-23 07:32 UTC, simskij commented
As @rreinurm seems to be MiA and this issue isn't something I'd say is prioritized, i'll go ahead and close this PR. If this where to be changed in the future, the path @stffabi and @wmbutler where steering against would likely be the preferred solution.

Thanks.

2019-04-23 07:32 UTC, closed without merging