Add argument for setting priority level of Gotify notifications
containrrr/watchtower pull request #585
Opened 2020-06-25 02:34 UTC by bdr99

I noticed that the priority setting for Gotify notifications was hardcoded as 0. This PR adds an argument, `--notification-gotify-priority` or `WATCHTOWER_NOTIFICATION_GOTIFY_PRIORITY`, to allow the user to set the priority. I kept 0 as the default value.

2020-06-29 16:59 UTC, victorcmoura requested changes
Thank you for your contribution! =)

The implementation itself looks good, due to the default value, it shouldn't affect running instances.

I only missed some instructions in the arguments documentation section. Would you mind adding your contribution to [arguments doc](https://github.com/containrrr/watchtower/blob/master/docs/arguments.md) as well?

2020-06-29 18:09 UTC, bdr99 commented
@victorcmoura It doesn't look like any of the other notification-related arguments are mentioned in the arguments doc. For example, I don't see `--notification-gotify-url`, `--notification-email-to`, or even `--notifications` documented there. I think this omission is outside the scope of this PR.

2020-06-30 13:17 UTC, victorcmoura commented
Well pointed @bdr99, there really isn't any argument docs in this file. But, since it is actually an argument, there should be no reason not to document them.

@simskij can you help us with this? Is there any reason not to document this arguments?

2020-08-08 16:47 UTC, simskij commented
Thank you for your contribution!

Unfortunately, as all watchtower-native notification services will soon be replaced by shoutrrr adapters, I suggest you instead have a stab at implementing this there, as part of the URL: https://github.com/containrrr/shoutrrr

Merging this code would only lead to the feature being available for a short while and then disappearing again.

2020-08-08 16:47 UTC, closed without merging