Disabling color through environment variables
containrrr/watchtower pull request #598
Opened 2020-07-08 17:07 UTC by bugficks

This patch adds support for disabling color through environment variables.

- NO_COLOR: https://no-color.org/
- CLICOLOR,CLICOLOR_FORCE: https://bixense.com/clicolors/ ([logrus built-in](https://github.com/sirupsen/logrus/blob/6699a89a232f3db797f2e280639854bbc4b89725/text_formatter.go#L46))

2020-07-08 19:21 UTC, piksel commented on cmd/root.go
> +		})
Probably not a good idea, see #562

2020-07-09 07:43 UTC, bugficks commented
I have seen this PR#562 but it changes rather important defaults while
this patch disables coloring only if user has set some environment
variable.
Without those env vars everything stays the same.

I could have added a command line param but I have opt-ed for some
standard way.
If this really isn't acceptable I might go that route though.


On 08.07.2020 21:21, nils måsén wrote:
> *@piksel* commented on this pull request.
> 
> ------------------------------------------------------------------------
> 
> In cmd/root.go
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcontainrrr%2Fwatchtower%2Fpull%2F598%23discussion_r451773125&data=02%7C01%7C%7C2b103bdbde674234f3af08d823742aa3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637298329117617631&sdata=obVbD8888SwL%2BbPnqCT7fhx7JS8Q9pnSHCNqfMnhE5w%3D&reserved=0>:
> 
>> +		log.SetFormatter(&log.TextFormatter{
> +			EnvironmentOverrideColors: true,
> +		})
> 
> Probably not a good idea, see #562
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcontainrrr%2Fwatchtower%2Fpull%2F562&data=02%7C01%7C%7C2b103bdbde674234f3af08d823742aa3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637298329117627625&sdata=fQBqmd%2FlY7IZriL9yFyGZPnU8NuoZhI%2BSvew0NdPgP8%3D&reserved=0>
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcontainrrr%2Fwatchtower%2Fpull%2F598%23pullrequestreview-445061828&data=02%7C01%7C%7C2b103bdbde674234f3af08d823742aa3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637298329117627625&sdata=gn9JD%2FtYUd7%2B6ot2Iu36Se6C0pdCq%2B4BiYBFC1EKg9o%3D&reserved=0>,
> or unsubscribe
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAW2V77SMDDWJRDXV7J4ALTR2TBM5ANCNFSM4OUYWXCQ&data=02%7C01%7C%7C2b103bdbde674234f3af08d823742aa3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637298329117637619&sdata=6hnEXbhO9S%2B83C4%2F%2BV%2BxmXDHJ294nYRG47wPwnSE%2BNE%3D&reserved=0>.
>

2020-07-09 08:54 UTC, piksel commented
Yeah, I noticed, so I removed the comment. I don't think there is any issues with this.

2020-07-21 13:21 UTC, piksel approved these changes

2020-08-08 16:58 UTC, simonaronsson requested changes
Thank you for your contribution! While I really like the feature you've added, I'd kindly like to ask you to implement it the same way as all other flags and env vars in watchtower, namely in https://github.com/containrrr/watchtower/blob/master/internal/flags/flags.go using viper and cobra. I'd also like to ask you to document this feature in https://github.com/containrrr/watchtower/blob/master/docs/arguments.md

Thanks again. 🙇

2020-08-08 16:58 UTC, simskij commented on cmd/root.go
> +	if _, enabled := os.LookupEnv("NO_COLOR"); enabled {
Should be implemented the same way as all other flags and env vars.

2020-08-12 12:25 UTC, piksel approved these changes

2020-08-21 20:54 UTC, merged

2020-08-21 20:54 UTC, simonaronsson commented
@all-contributors add @bugficks for code

2020-08-21 20:54 UTC, simonaronsson commented
Thank you for your contribution! 🙇