reduce noise on notifications
containrrr/watchtower pull request #716
Opened 2020-12-21 16:41 UTC by tkalus

Some private registries do not support HEAD (E.G. GitLab Container Registry).
With the current config, this log message is causing a notification to be
sent for each container hosted in a registry lacking HEAD support.

Reducing this to `log.Debug()` matches statements around it while still
being able to retain notifications of container stops, starts, and
updates.

2020-12-21 16:47 UTC, tkalus commented
In my case, I'm getting 48 noop notifications per hour:
- three containers in GitLab Container Registry
- two identical VMs behind a LB for HA
- 15 minute checks
- email and Slack notifications

I'm _hoping_ this is in time for the next tagged release -- and that it's soon.

2020-12-21 17:15 UTC, simskij commented
Hi,

Thank you for your contribution! We'll definitely consider this in case we're unable to get HEAD to work consistently. However, I'd like to wait for `v1.1.1` to be rolled out first to see how many false positives we actually get post that.

In the best of worlds, we'll be able to keep logs of failing head requests as a warning for when DockerHub users are consuming their rate limit - without spamming you in the progress.

If it's still too noisy post that, and we come to the conclusion that we're out of options, we'll make a fast patch release with your changes.

Best,
Simme

2020-12-21 17:32 UTC, tkalus commented
Hey @simskij, thanks for the consideration.

Totally agree with the need for visibility when it comes to Docker Hub API consumption -- and I agree with the idea of only checking HEAD on dockerhub.

I'll bring it up in issue 715 too, but one idea might be _keep_ the check for all containers/registries but selectively `log.Debug()` or `log.Warning()` based on the registry hostname?

2020-12-22 00:43 UTC, tkalus commented
Updated with one _possible_ way.  Golang isn't my one of my primary languages, so I'm not going to feel bad at all if this isn't up to y'alls standards or deviates too far from the established patterns.

I managed to confirm it works by dint of live testing.

Here are the relevant log files with some light redaction:
```
watchtower    | time="2020-12-22T00:28:35Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/tkalus-forks/watchtower/manifests/latest"
watchtower    | time="2020-12-22T00:28:35Z" level=warning msg="Could not do a head request, falling back to regular pull." container=/watchtower image="tkalus-forks/watchtower:latest"
watchtower    | time="2020-12-22T00:28:35Z" level=debug msg="Reason: registry responded to head request with &{401 Unauthorized 401 HTTP/1.1 1 1 map[Content-Length:[166] Content-Type:[application/json] Date:[Tue, 22 Dec 2020 00:28:35 GMT] Docker-Distribution-Api-Version:[registry/2.0] Strict-Transport-Security:[max-age=31536000] Www-Authenticate:[Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:tkalus-forks/watchtower:pull\",error=\"insufficient_scope\"]] {} 166 [] false false map[] 0xc000432c00 0xc00044c4d0}"
watchtower    | time="2020-12-22T00:28:35Z" level=debug msg="Pulling image" container=/watchtower image="tkalus-forks/watchtower:latest"
watchtower    | time="2020-12-22T00:28:36Z" level=debug msg="Error pulling image tkalus-forks/watchtower:latest, Error response from daemon: pull access denied for tkalus-forks/watchtower, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
watchtower    | time="2020-12-22T00:28:36Z" level=info msg="Unable to update container \"/watchtower\": Error response from daemon: pull access denied for tkalus-forks/watchtower, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next."
...
watchtower    | time="2020-12-22T00:28:37Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://registry.gitlab.com/v2/<snip:gitlab_org>/<snip:gitlab_repo>/manifests/latest"
watchtower    | time="2020-12-22T00:28:37Z" level=debug msg="Could not do a head request, falling back to regular pull."
watchtower    | time="2020-12-22T00:28:37Z" level=debug msg="Reason: registry responded to head request with &{401 Unauthorized 401 HTTP/1.1 1 1 map[Content-Length:[160] Content-Type:[application/json] Date:[Tue, 22 Dec 2020 00:28:37 GMT] Docker-Distribution-Api-Version:[registry/2.0] Www-Authenticate:[Bearer realm=\"https://gitlab.com/jwt/auth\",service=\"container_registry\",scope=\"repository:<snip:gitlab_org>/<snip:gitlab_repo>:pull\",error=\"insufficient_scope\"] X-Content-Type-Options:[nosniff]] {} 160 [] false false map[] 0xc000433e00 0xc00044cf20}"
watchtower    | time="2020-12-22T00:28:37Z" level=debug msg="Pulling image" container=/<snip:gitlab_repo> image="registry.gitlab.com/<snip:gitlab_org>/<snip:gitlab_repo>:latest"
watchtower    | time="2020-12-22T00:28:38Z" level=debug msg="No new images found for /<snip:gitlab_repo>"
...
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg="Doing a HEAD request to fetch a digest" url="https://index.docker.io/v2/library/traefik/manifests/v2.1"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg="Found a remote digest to compare with" remote="sha256:ab83baa3d198ee5a2fd685bed96417055a2bdd271efe11a0b831d6c02436aabd"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg=Comparing local="sha256:2c17c789b4913f29d1f64199cc3d9110f77fc3f7d6bafb306520d9e377efff96" remote="sha256:ab83baa3d198ee5a2fd685bed96417055a2bdd271efe11a0b831d6c02436aabd"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg=Comparing local="sha256:ab83baa3d198ee5a2fd685bed96417055a2bdd271efe11a0b831d6c02436aabd" remote="sha256:ab83baa3d198ee5a2fd685bed96417055a2bdd271efe11a0b831d6c02436aabd"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg="Found a match"
watchtower    | time="2020-12-22T00:28:39Z" level=debug msg="No pull needed. Skipping image."
```

The error on the 'full-pull' for `tkalus-forks/watchtower` is expected -- and demonstrates the reduced noise v. desired alerting nicely.

2020-12-22 16:42 UTC, simskij requested changes
Looks really good! Some minor nitpicks, but other than that I think we're ready to roll 👍 🎉 Thanks for helping out! 🙏

2020-12-22 16:42 UTC, simskij commented on pkg/registry/registry.go
> +	if containerHost == "index.docker.io" {
This should also include ghcr.io

2020-12-22 16:42 UTC, simskij commented on pkg/container/client.go
> +		if registry.WarnOnAPIComsumption(container) {
```suggestion
		if registry.WarnOnAPIConsumption(container) {
```

2020-12-22 16:42 UTC, simskij commented on pkg/registry/registry.go
> +func WarnOnAPIComsumption(container watchtowerTypes.Container) bool {
```suggestion
// WarnOnAPIConsumption will return true if the registry is knonw-expected to respond to HTTP HEAD in checking the container digest; will return false if behavior is unknown.
func WarnOnAPIConsumption(container watchtowerTypes.Container) bool {
```

2020-12-22 17:48 UTC, tkalus commented
@simskij Based on the comments in Issue 715, it seems as though GitLab Registry are the ones still suffering heartburn.  It appears they have a URL pathname pattern for the manifests that's different from DockerHub, GitHub, GCR, and others.

**Any objection to flipping the logic so it `Warn`s on everything _but_ `registry.gitlab.com`?**

Strange thing is that GitLab Registry _does_ respond appropriately to the command `docker manifest inspect`, so it _is_ able to pull the manifest -- somehow.  I might see about running `docker manifest inspect` through `mitmproxy` to see what pathnames are being pulled if I find some time over my holiday downtime.

2020-12-22 21:17 UTC, simskij commented
I think the previous approach with only making them info-level for DockerHub probably will work better, as that's the only case (right now) where it actually makes any real difference for the user. In the other cases, if it works then good, otherwise no harm, right?

2020-12-22 21:24 UTC, tkalus commented
Totally reasonable to me.  💯 agree: local, private-network registries will be hard to enumerate and _probably_ shouldn't be notifying anyway.

Will revert and push in just a moment -- `Warn` on `index.docker.io` and `ghcr.io` and `Debug` on others.

2020-12-22 23:48 UTC, simskij commented
Awesome! Thanks a bunch for your help with this!

2020-12-22 23:48 UTC, simskij commented
@all-contributors add @tkalus for code

2020-12-22 23:48 UTC, merged