Add timeout parameter
containrrr/watchtower pull request #74
Opened 2017-03-24 22:43 UTC by Robotex

These changes add the timeout parameter for #69 
I just learnt the basics of Go from a quick read of their Playground tutorial, so I apologize for any mistake

2017-04-30 22:53 UTC, bradleyfalzon commented
I'm not a maintainer, but the cli package does have a DurationFlag (https://godoc.org/github.com/urfave/cli#DurationFlag) which may be a better option so you don't need to do the cast to time.Duration.

2017-11-06 22:31 UTC, napstr commented on main.go
> +			Usage:	"timeout before container is forcefully stopped",
I suggest saying "timeout **in seconds** before container is forcefully stopped", to be more clear

2018-03-02 14:30 UTC, stffabi commented
@Robotex thanks for your contribution. I like the idea of @bradleyfalzon to use the duration flag and we should also add some documentation on the README.md.

Would it be possible for you to make these changes?

2018-03-03 01:29 UTC, Robotex commented
I have made and committed the requested changes, however ATM I don't have the build environment set up so I cannot test them. Feel free to review and comment if you encounter any compilation errors.

2018-03-03 10:10 UTC, stffabi requested changes
Thanks @Robotex for your work and adjustments. I have only two little comments.

Would be great if you could take a look into those.

2018-03-03 10:10 UTC, stffabi commented on README.md
> +* `--timeout` Timeout before the container is forcefully stopped. When set, this option will change the default (`10s`) wait time to the given value. An example: `--timeout 30s` will set the timeout
What would you think about naming the option `--stop-timeout`? This makes it more clear what timeout this is.

2018-03-03 10:10 UTC, stffabi commented on main.go
> +	timeout = c.GlobalDuration("timeout")
Timeout could be negative, we should check for that and print out an error.

2018-03-03 20:46 UTC, stffabi approved these changes

2018-03-03 20:47 UTC, stffabi commented
LGTM, thanks for your contribution. I'll just squash your commits and then merge it in.

2018-03-03 20:54 UTC, merged

2018-07-19 21:44 UTC, reloxx13 commented
pls check this: #195

--stop-timeout not found in armhf-0.3