add ghcr
containrrr/watchtower pull request #850
Opened 2021-03-15 03:25 UTC by ksurl

cleaned up version of https://github.com/containrrr/watchtower/pull/808

PR for https://github.com/containrrr/watchtower/issues/722

## PREREQUISITES  
* create github personal access token with permissions for read/write packages as seen [here](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images)
* add the token as a repo environment variable named GITHUB_PASSWORD
* enable enhanced container support in profile settings (optional?)

## POST MERGE  
* after first build has been published, package needs to be made public (defaults to private)

2021-04-17 13:32 UTC, piksel commented
Haha, the name of the secret needs to be changed. Github did not like that one :D
![image](https://user-images.githubusercontent.com/807383/115114922-0f8ef200-9f92-11eb-9cb5-89eeccc6ab17.png)

2021-04-17 13:53 UTC, piksel requested changes
Suggested the configured secrets

2021-04-17 13:53 UTC, piksel commented on .github/workflows/release-dev.yaml
> +        password: ${{ secrets.GITHUB_PASSWORD }}
```suggestion
        username: ${{ secrets.BOT_USERNAME }}
        password: ${{ secrets.BOT_GHRC_PAT }}
```

2021-04-17 13:53 UTC, piksel commented on .github/workflows/release.yml
> +          echo "$GITHUB_PASSWORD" | docker login -u ${{ github.repository_owner }} --password-stdin && \
```suggestion
          echo "$BOT_GHRC_PAT" | docker login -u $BOT_USERNAME --password-stdin && \
```

2021-04-17 16:38 UTC, simskij commented on .github/workflows/release-dev.yaml
> +        password: ${{ secrets.GITHUB_PASSWORD }}
@piksel `BOT_GHRC_PAT` -> `BOT_GHCR_PAT` though :)

2021-04-17 16:38 UTC, simskij commented on .github/workflows/release.yml
> +          echo "$GITHUB_PASSWORD" | docker login -u ${{ github.repository_owner }} --password-stdin && \
same here

2021-04-17 19:09 UTC, piksel commented
Tested just pushing the current `latest` to GHRC using the credentials above. It works, and should work with this action as well.

2021-04-18 00:54 UTC, ksurl commented
looks good. once it is merged, it should start pushing all new versioned and latest builds to it and mirror docker hub?

2021-04-19 18:12 UTC, piksel commented on .github/workflows/release.yml
> +          echo "$BOT_GHRC_PAT" | docker login -u $BOT_USERNAME --password-stdin && \
```suggestion
          echo "$BOT_GHCR_PAT" | docker login -u $BOT_USERNAME --password-stdin && \
```

2021-04-19 18:12 UTC, piksel commented on .github/workflows/release-dev.yaml
> +        password: ${{ secrets.BOT_GHRC_PAT }}
```suggestion
        password: ${{ secrets.BOT_GHCR_PAT }}
```

2021-04-19 18:18 UTC, piksel approved these changes

2021-04-20 10:49 UTC, piksel requested changes
The annotations needs to be done for every repo and cannot be altered to include both at the same time. They link `tag_from_arg1` to `tag_from_arg2`, so providing four arguments doesn't do what was intended.

2021-04-20 10:49 UTC, piksel commented on .github/workflows/release.yml
>              --variant v8
```suggestion
      - name: Annotate manifest for latest
        run: |
          for REPO in '' ghrc.io/ ; do

          docker manifest annotate \
            ${REPO}containrrr/watchtower:latest \
            ${REPO}containrrr/watchtower:i386-latest \
            --os linux \
            --arch 386
      
          docker manifest annotate \
            ${REPO}containrrr/watchtower:latest \
            ${REPO}containrrr/watchtower:armhf-latest \
            --os linux \
            --arch arm
            
          docker manifest annotate \
            ${REPO}containrrr/watchtower:latest \
            ${REPO}containrrr/watchtower:arm64v8-latest \
            --os linux \
            --arch arm64 \
            --variant v8

          done
```

2021-04-20 10:49 UTC, piksel commented on .github/workflows/release.yml
>              --variant v8
```suggestion
        run: |
          for REPO in '' ghrc.io/ ; do
          
          docker manifest annotate \
            ${REPO}containrrr/watchtower:$(echo $TAG | sed 's/^v*//') \
            ${REPO}containrrr/watchtower:i386-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch 386
          
          docker manifest annotate \
            ${REPO}containrrr/watchtower:$(echo $TAG | sed 's/^v*//') \
            ${REPO}containrrr/watchtower:armhf-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch arm
      
          docker manifest annotate \
            ${REPO}containrrr/watchtower:$(echo $TAG | sed 's/^v*//') \
            ${REPO}containrrr/watchtower:arm64v8-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch arm64 \
            --variant v8
            
            done
```

2021-04-20 12:06 UTC, simskij approved these changes

2021-04-20 12:06 UTC, merged

2021-04-22 13:13 UTC, simonaronsson commented
@all-contributors add @ksurl for code